from django.db import models

class MstMusic(models.Model):
    """曲マスタ"""
    class Meta:
        db_table = 'mst_music'

    music_name \
        = models.TextField()
    music_deleted_flag \
        = models.BooleanField()
    artist_name \
        = models.TextField()
    genre \
        = models.TextField()
    difficulty_code \
        = models.CharField(max_length=1)
    bpm_min \
        = models.PositiveSmallIntegerField()
    bpm_max \
        = models.PositiveSmallIntegerField()
    level \
        = models.PositiveSmallIntegerField()
    sp_notes_num_all \
        = models.PositiveSmallIntegerField()
    sp_notes_num_scr \
        = models.PositiveSmallIntegerField()
    sp_notes_num_cn \
        = models.PositiveSmallIntegerField()
    sp_notes_num_bss \
        = models.PositiveSmallIntegerField()
    sp_score_max \
        = models.PositiveSmallIntegerField()
    sp_score_border_maxminus \
        = models.PositiveSmallIntegerField()
    sp_score_border_aaa \
        = models.PositiveSmallIntegerField()
    sp_score_border_aa \
        = models.PositiveSmallIntegerField()
    sp_score_border_a \
        = models.PositiveSmallIntegerField()
    dp_notes_num_all \
        = models.PositiveSmallIntegerField()
    dp_notes_num_scr \
        = models.PositiveSmallIntegerField()
    dp_notes_num_cn \
        = models.PositiveSmallIntegerField()
    dp_notes_num_bss \
        = models.PositiveSmallIntegerField()
    dp_score_max \
        = models.PositiveSmallIntegerField()
    dp_score_border_maxminus \
        = models.PositiveSmallIntegerField()
    dp_score_border_aaa \
        = models.PositiveSmallIntegerField()
    dp_score_border_aa \
        = models.PositiveSmallIntegerField()
    dp_score_border_a \
        = models.PositiveSmallIntegerField()
    db_notes_num_all \
        = models.PositiveSmallIntegerField()
    db_notes_num_scr \
        = models.PositiveSmallIntegerField()
    db_notes_num_cn \
        = models.PositiveSmallIntegerField()
    db_notes_num_bss \
        = models.PositiveSmallIntegerField()
    db_score_border_maxminus \
        = models.PositiveSmallIntegerField()
    db_score_border_aaa \
        = models.PositiveSmallIntegerField()
    db_score_border_aa \
        = models.PositiveSmallIntegerField()
    db_score_border_a \
        = models.PositiveSmallIntegerField()
    db_withscr_notes_num_all \
        = models.PositiveSmallIntegerField()
    db_withscr_notes_num_scr \
        = models.PositiveSmallIntegerField()
    db_withscr_notes_num_cn \
        = models.PositiveSmallIntegerField()
    db_withscr_notes_num_bss \
        = models.PositiveSmallIntegerField()
    db_withscr_score_border_maxminus \
        = models.PositiveSmallIntegerField()
    db_withscr_score_border_aaa \
        = models.PositiveSmallIntegerField()
    db_withscr_score_border_aa \
        = models.PositiveSmallIntegerField()
    db_withscr_score_border_a \
        = models.PositiveSmallIntegerField()
    note_page_url \
        = models.TextField()
    ins_user \
        = models.TextField()
    ins_date \
        = models.DateTimeField()
    upd_user \
        = models.TextField()
    upd_date \
        = models.DateTimeField()
