version: '3.7'
services:
    # TODO: Nginx経由でPythonアプリにアクセスできるようにする（Nginx＆Gunicorn）。
    # TODO: .env配置例
    #       https://qiita.com/mokemokechicken/items/d7384a4d8cdc344e7b4a
    django:
        build:
          context: ./
          dockerfile: ./docker/django/Dockerfile
        container_name: dabubato_django
        command: sh -c "dockerize -timeout 300s -wait tcp://postgres:5432 -wait-retry-interval 5s pipenv run python /usr/src/app/manage.py migrate && pipenv run python /usr/src/app/manage.py runserver 0.0.0.0:8000"
        expose: 
          - "8000"
        ports:
        - "8000:8000"
        environment:
            - DEBUG=1
            - DATABASE_HOST=postgres
    postgres:
        build: ./docker/postgres/
        container_name: dabubato_postgres
        expose: 
            - "55432"
        ports:
            - "55432:5432"
        environment:
            # TODO: envファイルに外出ししたほうがいいかも
            POSTGRES_PASSWORD: postgres